user:
  outputs:
    default:
      account: NJTQSJW-LI30813
      auth_type: password
      client_session_keep_alive: false
      connect_retries: 3
      connect_timeout: 30
      database: MUSIC_KPI
      password: Snowflake@1990
      retry_on_database_errors: true
      role: null
      schema: dbt_amistry
      type: snowflake
      user: mistryamit03
      warehouse: MUSIC_KPI_WH
  target: default
